{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "UMSL002.serviceAccountName" . }}
  labels:
{{ include "UMSL002.labels" . | indent 4 }}
{{- end -}}
